name: Test

on: ['push', 'pull_request']

jobs:
  build-snap:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v4
     - uses: snapcore/action-build@v1
       id: snapcraft-build
       with:
         snapcraft-args: "-v"
     - uses: actions/upload-artifact@v4
       with:
         name: ${{ steps.snapcraft-build.outputs.snap }}
         path: ${{ steps.snapcraft-build.outputs.snap }}
